config/routes.rb
DojoSampleApp::Application.routes.draw do
  resources :tennis

end

app/models/tenni.rb
class Tenni < ActiveRecord::Base
  attr_accessible :ganador, :jugador1, :jugador2, :p1, :p2
  
  
  def Apuntar(jugador)
    puntajes = [0, 15, 30, 40, 41]
    
    if jugador==jugador1
      self.p1 = puntajes[puntajes.index(self.p1) + 1]  
    end
    
    if jugador==jugador2
      self.p2 = puntajes[puntajes.index(self.p2) + 1]
    end  
    
    ValidarIguales()
    ValidarGanador(jugador)
    
  end
  
  def ValidarIguales()
    if (self.p1 == 40) && (self.p2 == 40)
      self.p1 = 30
      self.p2 = 30
    end
  end
  
  def ValidarGanador(jugador)
    if (self.p1 == 41 || self.p2 == 41)
      puts "El ganador es #{jugador}"
    end
  end
  
    def MostrarPuntaje(jugador)
      if jugador==jugador1
        puts "El puntaje del jugador 1 es #{p1}"  
      end
      
      if jugador==jugador2
        puts "El puntaje del jugador 12es #{p2}"
      end  
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tennis_controller.rb
class TennisController < ApplicationController
  # GET /tennis
  # GET /tennis.json
  def index
    @tennis = Tenni.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tennis }
    end
  end

  # GET /tennis/1
  # GET /tennis/1.json
  def show
    @tenni = Tenni.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tenni }
    end
  end

  # GET /tennis/new
  # GET /tennis/new.json
  def new
    @tenni = Tenni.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tenni }
    end
  end

  # GET /tennis/1/edit
  def edit
    @tenni = Tenni.find(params[:id])
  end

  # POST /tennis
  # POST /tennis.json
  def create
    @tenni = Tenni.new(params[:tenni])

    respond_to do |format|
      if @tenni.save
        format.html { redirect_to @tenni, notice: 'Tenni was successfully created.' }
        format.json { render json: @tenni, status: :created, location: @tenni }
      else
        format.html { render action: "new" }
        format.json { render json: @tenni.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tennis/1
  # PUT /tennis/1.json
  def update
    @tenni = Tenni.find(params[:id])

    respond_to do |format|
      if @tenni.update_attributes(params[:tenni])
        format.html { redirect_to @tenni, notice: 'Tenni was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tenni.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tennis/1
  # DELETE /tennis/1.json
  def destroy
    @tenni = Tenni.find(params[:id])
    @tenni.destroy

    respond_to do |format|
      format.html { redirect_to tennis_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tennis_helper.rb
module TennisHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DojoSampleApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tennis/_form.html.erb
<%= form_for(@tenni) do |f| %>
  <% if @tenni.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tenni.errors.count, "error") %> prohibited this tenni from being saved:</h2>

      <ul>
      <% @tenni.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :jugador1 %><br />
    <%= f.text_field :jugador1 %>
  </div>
  <div class="field">
    <%= f.label :jugador2 %><br />
    <%= f.text_field :jugador2 %>
  </div>
  <div class="field">
    <%= f.label :p1 %><br />
    <%= f.number_field :p1 %>
  </div>
  <div class="field">
    <%= f.label :p2 %><br />
    <%= f.number_field :p2 %>
  </div>
  <div class="field">
    <%= f.label :ganador %><br />
    <%= f.text_field :ganador %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tennis/edit.html.erb
<h1>Editing tenni</h1>

<%= render 'form' %>

<%= link_to 'Show', @tenni %> |
<%= link_to 'Back', tennis_path %>

app/views/tennis/index.html.erb
<h1>Listing tennis</h1>

<table>
  <tr>
    <th>Jugador1</th>
    <th>Jugador2</th>
    <th>P1</th>
    <th>P2</th>
    <th>Ganador</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tennis.each do |tenni| %>
  <tr>
    <td><%= tenni.jugador1 %></td>
    <td><%= tenni.jugador2 %></td>
    <td><%= tenni.p1 %></td>
    <td><%= tenni.p2 %></td>
    <td><%= tenni.ganador %></td>
    <td><%= link_to 'Show', tenni %></td>
    <td><%= link_to 'Edit', edit_tenni_path(tenni) %></td>
    <td><%= link_to 'Destroy', tenni, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tenni', new_tenni_path %>

app/views/tennis/new.html.erb
<h1>New tenni</h1>

<%= render 'form' %>

<%= link_to 'Back', tennis_path %>

app/views/tennis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Jugador1:</b>
  <%= @tenni.jugador1 %>
</p>

<p>
  <b>Jugador2:</b>
  <%= @tenni.jugador2 %>
</p>

<p>
  <b>P1:</b>
  <%= @tenni.p1 %>
</p>

<p>
  <b>P2:</b>
  <%= @tenni.p2 %>
</p>

<p>
  <b>Ganador:</b>
  <%= @tenni.ganador %>
</p>


<%= link_to 'Edit', edit_tenni_path(@tenni) %> |
<%= link_to 'Back', tennis_path %>